### ISSUE TITLE
Compilation error: cout not a member of std

### ISSUE THREAD

**Issue by s-tikhomirov** [ivanpustogarov/bcclient#2]
On `make` of libbitcoin (Ubuntu 16.04.3 LTS):

```
utility/mnemonic.cpp: In function ‘const string libbitcoin::decode_mnemonic(const string_list&)’:
utility/mnemonic.cpp:1704:5: error: ‘cout’ is not a member of ‘std’
     std::cout << std::endl;
     ^
Makefile:603: recipe for target 'utility/mnemonic.lo' failed
make[1]: *** [utility/mnemonic.lo] Error 1
make[1]: Leaving directory '/home/sergei/Documents/research/code/bcclient/bcclient/libbitcoin/src'
Makefile:511: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

Solved by adding `#include<iostream>` to `/libbitcoin/src/utility/mnemonic.cpp` and also to `/main.cpp` (same error popped up on second `make`). Not sure this is the proper way though.

**Comment by ivanpustogarov** [comment]
Could you please confirm that these changes also work on Ubuntu 14.04?

**Comment by s-tikhomirov** [comment]
Will try (not right away though).

**Comment by s-tikhomirov** [comment]
Tried it on Ubuntu 14.04.5 (live USB). It compiles both with and without the changes.
